# Generated by Django 2.2.6 on 2019-10-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191026_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in U$S', max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='subs',
            name='extras',
            field=models.ManyToManyField(blank=True, to='orders.SubExtra'),
        ),
    ]
