# Generated by Django 2.2.6 on 2019-10-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191026_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DinnerPlatters',
            new_name='DinnerPlatter',
        ),
        migrations.RenameModel(
            old_name='Salads',
            new_name='Salad',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(choices=[('1', 'One topping'), ('2', 'Two toppings'), ('3', 'Three toppings')], default=('1', 'One topping'), max_length=64),
            preserve_default=False,
        ),
    ]
