# Generated by Django 2.2.6 on 2019-10-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191026_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
