# Generated by Django 2.2.6 on 2019-10-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delete_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('regular', 'Regular'), ('sicilian', 'Sicilian')], max_length=10)),
                ('size', models.CharField(choices=[('S', 'small'), ('L', 'Large')], max_length=10)),
                ('price', models.FloatField()),
                ('toppings', models.CharField(choices=[('1', 'One topping'), ('2', 'Two toppings'), ('3', 'Three toppings')], max_length=64)),
            ],
        ),
    ]
