# Generated by Django 2.2.6 on 2019-11-07 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0005_remove_sub_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in U$S', max_digits=6)),
                ('dinnerPlatter', models.ManyToManyField(blank=True, to='orders.DinnerPlatter')),
                ('pasta', models.ManyToManyField(blank=True, to='orders.Pasta')),
                ('pizza', models.ManyToManyField(blank=True, to='orders.Pizza')),
                ('salad', models.ManyToManyField(blank=True, to='orders.Salad')),
                ('sub', models.ManyToManyField(blank=True, to='orders.Sub')),
                ('subExtra', models.ManyToManyField(blank=True, to='orders.SubExtra')),
                ('topping', models.ManyToManyField(blank=True, to='orders.Topping')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
